[package]
name = "packer"
version = "0.1.0"
authors = ["Thomas Beckley <thomas@tbeckley.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rand = "*"